
->Handles multidimension data
-> GPU Acceleration and Numerical computation'
-> can hav diff no of dim, determines the rank.
->1d tensor : vector; 2d tensor - matrix, more than 2 d - ndim tensr


In [2]:
import torch
import numpy as np
#(creation)initialization with data driectly :
data=[[1,2],[3,4]]
tdata=torch.tensor(data)


In [3]:
#initialization torch using existing numpy array
arr=np.array(data) #tensor that shares the same underlying data buffer with the NumPy array, avoiding unnecessary data copying.
npar=torch.from_numpy(arr)
print(npar)

npar.numpy()#Convert tensor to numpy
print("As numpy: ",npar)


#torch.ones()  retains shape and datatype of tdata
x1=torch.ones_like(tdata)
print(x1)

#torch.rand()
x2=torch.rand_like(tdata,dtype=torch.float) # generate rand val and  override datatype of tdata
print(x2)

tensor([[1, 2],
        [3, 4]])
As numpy:  tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.5921, 0.0560],
        [0.5085, 0.7511]])


In [4]:
#supports various operation arithmetic operation, mathematical function, linear algebra opr, reduction opr,

https://pytorch.org/docs/stable/torch.html


https://pytorch.org/docs/stable/torch.html#math-operations



In [5]:
#support indexing and slicing operations to access specific elements or sub-tensors within a tensor

print(tdata[:1])
tdata[:1]=0
print(tdata)

tensor([[1, 2]])
tensor([[0, 0],
        [3, 4]])



https://pytorch.org/docs/stable/notes/broadcasting.html


In [34]:
#Bradcasting:
'''If the arrays have a different number of dimensions, the shape of the smaller array is padded with ones on its left side.
If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other array's shape.

#3x3 array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# 1x3 array
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)
Result of broadcasting addition:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
 '''

x=torch.empty(3,4,2) #creating a tensor with uninitialized values
y=torch.empty(3,4,2)
print(x)
print(y)
print(x+y)
# broadcast possible with same shape

x=torch.empty(4,3,2,1)
y=torch.empty( 3,1,1)
print(x)
print(y)
print(x+y)
# as matching trail, broadcasting possible

'''
#As mismatch trail broadcasting not possible
x=torch.empty(4,3,2,1)
y=torch.empty( 3,5,1)
print(x)
print(y)
print(x+y)
'''

tensor([[[1.2079e+07, 4.4020e-41],
         [3.6312e-31, 3.2041e-41],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])
tensor([[[1.2079e+07, 4.4020e-41],
         [2.2405e-31, 3.2041e-41],
         [1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00]]])
tensor([[[2.4157e+07, 8.8041e-41],
         [5.8718e-31, 6.4081e-41],
         [1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00]],

      

'\n#As mismatch trail broadcasting not possible\nx=torch.empty(4,3,2,1)\ny=torch.empty( 3,5,1)\nprint(x)\nprint(y)\nprint(x+y)\n'

In [10]:
#%matplotlib inline  --no need to explicitly give plot.show(), draw the plots immediately after the current cell

In [11]:
#creates rand,ones,zeros tensor with shape
shap=(4,5)
tr=torch.rand(shap)
t1=torch.ones(shap)
t0=torch.zeros(shap)

print(tr)
print(t1)
print(t0)

tensor([[0.7196, 0.3040, 0.6006, 0.4776, 0.7161],
        [0.6550, 0.5091, 0.4185, 0.9725, 0.5233],
        [0.4328, 0.1145, 0.6356, 0.1063, 0.0667],
        [0.2494, 0.1409, 0.8817, 0.7607, 0.0242]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [12]:
#
print(x3.shape)#shape of tensor
print(x3.dtype)#dtype of tensor
print(x3.device)#device tensor stored on

torch.Size([3, 2])
torch.int64
cpu


In [23]:
print(x3)
print(x3[:,1])#slicing 1st param - ':' before , represent all row, 2nd param-1 represent 2nd col
print(x3[2:,1])#slicing 1st param- 2: represent 2nd row full, 2nd - param represnt 1st column

x4=torch.rand(4,5)
print(x4)
print(x4[1:3,2:4])#slicing 1st param 1:3 where 1 is start val and after : end value -1 so it prints 2nd and 3rd row of, 2nd param 2 :4 where 2 is start val, after : is end val -1; which is 3rd and 4th column

tensor([[15, 25],
        [35, 45],
        [55, 65]])
tensor([25, 45, 65])
tensor([65])
tensor([[0.4327, 0.2401, 0.3066, 0.9098, 0.8469],
        [0.0228, 0.5721, 0.6479, 0.4918, 0.9110],
        [0.0099, 0.7267, 0.8656, 0.5436, 0.0436],
        [0.3853, 0.8697, 0.2427, 0.1861, 0.2386]])
tensor([[0.6479, 0.4918],
        [0.8656, 0.5436]])


In [50]:
#stack with seperate dimension ; stack expects each tensor to be equal size, if x2=torch.tensor([[6,7],[8,9],[10,11]]) => error: got [2, 2] at entry 0 and [3, 2] at entry 2
print("tdata",tdata)
print("x1: ", x1)
x2=torch.tensor([[6,7],[8,9]])
x1i=torch.stack([tdata,x1, x2])

x1i

tdata tensor([[0, 0],
        [3, 4]])
x1:  tensor([[1, 1],
        [1, 1]])


tensor([[[0, 0],
         [3, 4]],

        [[1, 1],
         [1, 1]],

        [[6, 7],
         [8, 9]]])

In [51]:
#concat seq of tensor in the same dim
print("tdata",tdata)
print("x1: ", x1)
x2=torch.tensor([[6,7],[8,9],[10,11]])
x1i=torch.cat([tdata,x1, x2])

x1i

tdata tensor([[0, 0],
        [3, 4]])
x1:  tensor([[1, 1],
        [1, 1]])


tensor([[ 0,  0],
        [ 3,  4],
        [ 1,  1],
        [ 1,  1],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [63]:
#multiplying tensor used for dot product
print("x2: ", x2)
x3=torch.tensor([[10,20],[30,40],[50,60]])
print("x3: ", x3)
mulx=x2.mul(x3)
mulx

#alternatives
mulx=x2*x3
print(mulx)

x3trnsp=x3.T
mtrxmul=x2.matmul(x3trnsp)
print(mtrxmul)

mtrx_at=x2@x3trnsp
print(mtrx_at)

x2:  tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])
x3:  tensor([[10, 20],
        [30, 40],
        [50, 60]])
tensor([[ 60, 140],
        [240, 360],
        [500, 660]])
tensor([[ 200,  460,  720],
        [ 260,  600,  940],
        [ 320,  740, 1160]])
tensor([[ 200,  460,  720],
        [ 260,  600,  940],
        [ 320,  740, 1160]])


In [70]:
#transpose using .t_()
print("x3: ",x3)
x3trnsp=x3.t_()
x3trnsp

x3:  tensor([[10, 20],
        [30, 40],
        [50, 60]])


tensor([[10, 30, 50],
        [20, 40, 60]])

In [71]:
# without creating sepearate tensor it creates in same, (add_, mul_)
print("x3: ",x3)
x3.add_(5)
print(x3)

x3:  tensor([[10, 30, 50],
        [20, 40, 60]])
tensor([[15, 35, 55],
        [25, 45, 65]])


In [75]:
# without creating sepearate tensor it creates in same, (add_, mul_)
print("x3: ",x3)
x3.sub_(5) #subtract 5 from tensor x3, without sep tensor instead changes applied to x3
print(x3)

x3:  tensor([[ 5, 25, 45],
        [15, 35, 55]])
tensor([[ 0, 20, 40],
        [10, 30, 50]])


In [86]:
x4=np.ones(3)
print(x4)
x4np=torch.from_numpy(x4)
print(x4np)
np.add(x4np,3, out=x4) #add 3 to [1. 1. 1.], result(out/output ) store in same 'array '

[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


array([4., 4., 4.])

In [87]:
x4=np.ones(3)
print(x4)
x4np=torch.from_numpy(x4)
print(x4np)
np.multiply(x4np,3, out=x4) #multiply 3 to [1. 1. 1.], result(out/output ) store in same 'array '

[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


array([3., 3., 3.])